---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: acme

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: "1Gi"
