apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secret-key: {{ .Values.settings.secret | b64enc | quote }}

  db-host: {{ .Values.postgres.url | b64enc | quote }}
  db-port: {{ .Values.postgres.port | quote  | b64enc }}
  db-user: {{ .Values.postgres.user | b64enc | quote }}
  db-password: {{ .Values.postgres.password | b64enc | quote }}
  db-name: {{ .Values.postgres.database | b64enc | quote }}

  email-host: {{ .Values.email.url | b64enc | quote }}
  email-port: {{ .Values.email.port | quote | b64enc }}
  email-host-user: {{ .Values.email.user | b64enc | quote }}
  email-host-password: {{ .Values.email.password | b64enc | quote }}

  {{ if .Values.settings.dsn }}  sentry-dsn: {{ .Values.settings.dsn | b64enc | quote }}{{ end }}
