apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.settings.name }}-web
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}-web
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app.kubernetes.io/name: {{ .Values.settings.name }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
