---

- name: Deploy the Open Zaak apps in the cluster
  hosts: localhost

  vars_files:
    - vars/db_credentials.yml
    - vars/openzaak.yml
    - vars/opennotificaties.yml
    - vars/nlx.yml

  roles:
    - role: openzaak
      vars:
        openzaak_domain: gc-k8s-16cpu-64ram.openzaak.nl
        openzaak_db_host: "{{ db.privateIp }}"
        openzaak_db_port: "{{ db.port }}"
        openzaak_replicas: 3
        # openzaak_extra_hosts:
        #   - ingress-nginx-rsa4096.openzaak.nl
        #   - ingress-nginx-ec256.openzaak.nl
      tags:
        - openzaak

    - role: opennotificaties
      vars:
        opennotificaties_db_host: "{{ db.privateIp }}"
        opennotificaties_db_port: "{{ db.port }}"
        opennotificaties_domain: notificaties.gc-k8s-16cpu-64ram.openzaak.nl
        opennotificaties_replicas: 3
      tags:
        - opennotificaties

    - role: nlx
      vars:
        nlx_instance: test
        nlx_inway_self_address: inway.openzaak.nl
        nlx_inway_services:
          - name: openzaak-zaken
            endpoint_url: http://nginx.openzaak-test/zaken/api/v1
            documentation_url: https://test.openzaak.nl/zaken/
            authorization_model: none
            api_specification_document_url: https://test.openzaak.nl/zaken/api/v1/schema/openapi.json

          # - name: openzaak-documenten
          #   endpoint_url: https://test.openzaak.nl/documenten/api/v1
          #   documentation_url: https://test.openzaak.nl/documenten/
          #   authorization_model: none
          #   api_specification_document_url: https://test.openzaak.nl/documenten/api/v1/schema/openapi.json

          # - name: openzaak-catalogi
          #   endpoint_url: https://test.openzaak.nl/catalogi/api/v1
          #   documentation_url: https://test.openzaak.nl/catalogi/
          #   authorization_model: none
          #   api_specification_document_url: https://test.openzaak.nl/catalogi/api/v1/schema/openapi.json

          # - name: openzaak-besluiten
          #   endpoint_url: https://test.openzaak.nl/besluiten/api/v1
          #   documentation_url: https://test.openzaak.nl/besluiten/
          #   authorization_model: none
          #   api_specification_document_url: https://test.openzaak.nl/besluiten/api/v1/schema/openapi.json

          # - name: openzaak-authorizations
          #   endpoint_url: https://test.openzaak.nl/authorizations/api/v1
          #   documentation_url: https://test.openzaak.nl/authorizations/
          #   authorization_model: none
          #   api_specification_document_url: https://test.openzaak.nl/authorizations/api/v1/schema/openapi.json
      tags:
        - nlx
